spring:
  redis:
    host: localhost
    port: 8989

ustawienia:
  numerIndeksu: 461018
  wycena: "PROMO_CO_10_WYCEN"
  zamowienia: "POJEDYNCZE"
  zaopatrzenie: "GRUPOWE"
  wydarzenia: "INWENTARYZACJA"
  liczbaZadan: 200
